set nocompatible

" ----------------------------------------------------------------------------
"  Pathogen
" ----------------------------------------------------------------------------

runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#helptags()

" ----------------------------------------------------------------------------
"  Text Formatting
" ----------------------------------------------------------------------------

set autoindent
filetype plugin indent on
set tabstop=3
set shiftwidth=3


" ----------------------------------------------------------------------------
"  Remapping
" ----------------------------------------------------------------------------

" exit to normal mode with 'jj'
inoremap jj <ESC>

" sane movement with wrap turned on
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
nnoremap <Down> gj
nnoremap <Up> gk
vnoremap <Down> gj
vnoremap <Up> gk
inoremap <Down> <C-o>gj
inoremap <Up> <C-o>gk

" Gundo Key
nnoremap <F4> :GundoToggle<CR>
inoremap <F4> <C-o>:GundoToggle<CR>

" NERDTree Key
nnoremap <F3> :NERDTreeToggle<CR>
inoremap <F3> <C-o>:NERDTreeToggle<CR>

" Buffergator Key
nnoremap <F2> :BuffergatorToggle<CR>
inoremap <F2> <C-o>:BuffergatorToggle<CR>

" Make arrow keys n' shit wrap
set whichwrap+=<,>,h,l,[,]

" ----------------------------------------------------------------------------
"  UI
" ----------------------------------------------------------------------------

set ruler
set number
set scrolloff=3
set laststatus=2
set showmatch
set mat=1
set showcmd
set timeoutlen=2000

" Disable audible bell, enable visual bell.
set visualbell

" Wrapping preeeeetty
set cpoptions+=n
let &showbreak = '  │ '

" Code Folding
set foldmethod=indent
set foldnestmax=5
set foldlevel=3

" Syntax Highlighting
syntax on
colorscheme molokai

" Style indent guides
let g:indent_guides_auto_colors = 0
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_start_level = 1
hi! link IndentGuidesOdd Normal
hi! link IndentGuidesEven LineNr

" Configure clang completions
let g:clang_auto_select = 1
let g:clang_use_library = 1
let g:clang_complete_macros = 1
let g:clang_complete_patterns = 1

" Completion improvements

set completeopt=longest,menuone

" Mouse Selection
set selectmode+=mouse
set mouse=a

" Change the separator character to use vertical bar instead of pipe
set fillchars+=vert:│

" Hide scrollbars in GUI
set guioptions-=L
set guioptions-=r
