set nocompatible

" ----------------------------------------------------------------------------
"  Vundle
" ----------------------------------------------------------------------------

filetype off
set shell=/bin/bash\ -l
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

call vundle#end()
filetype plugin indent on
